# -*- coding: utf-8 -*-
"""
/***************************************************************************
 test2
                                 A QGIS plugin
 test2
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-06-09
        copyright            : (C) 2021 by test2
        email                : test2@test.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load test2 class from file test2.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .test2 import test2
    return test2(iface)
